# generated by datamodel-codegen:
#   filename:  job-protocol-v1.yaml
#   timestamp: 2026-09-04T14:56:36+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, confloat, conint, constr


class JobPriority(Enum):
    interactive = 'interactive'
    normal = 'normal'
    background = 'background'
    bulk = 'bulk'


class JobStatus(Enum):
    queued = 'queued'
    running = 'running'
    waiting = 'waiting'
    retrying = 'retrying'
    succeeded = 'succeeded'
    failed = 'failed'
    cancelled = 'cancelled'


class WaitingReason(Enum):
    input_required = 'input_required'
    approval_required = 'approval_required'
    dependency_unavailable = 'dependency_unavailable'
    connection_required = 'connection_required'
    paused = 'paused'


class JobCorrelationParent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    service: constr(min_length=1, max_length=100)
    job_id: constr(min_length=1, max_length=200)


class JobCorrelation(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    workflow_id: constr(max_length=200) | None = None
    parent: JobCorrelationParent | None = None


class JobSubmission(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: constr(min_length=1, max_length=100)
    priority: JobPriority
    deadline_at: AwareDatetime | None = None
    correlation: JobCorrelation
    input: dict[str, Any]


class JobProgress(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    phase: str
    message: str | None = None
    completed_units: confloat(ge=0.0) | None = None
    total_units: confloat(ge=0.0) | None = None


class JobTimestamps(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    created_at: AwareDatetime
    queued_at: AwareDatetime
    started_at: AwareDatetime | None = None
    heartbeat_at: AwareDatetime | None = None
    updated_at: AwareDatetime
    completed_at: AwareDatetime | None = None
    deadline_at: AwareDatetime | None = None
    expires_at: AwareDatetime | None = None
    next_attempt_at: AwareDatetime | None = None


class JobExecution(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    claim_generation: conint(ge=1) | None = None
    lease_expires_at: AwareDatetime | None = None


class JobError(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    code: str
    message: str
    retryable: bool
    details: dict[str, Any] | None = None


class JobLinks(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    self: str
    events: str
    events_poll: str
    cancel: str
    actions: str


class JobSnapshot(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocol_version: Literal['1.0']
    job_id: UUID
    job_type: str
    status: JobStatus
    status_reason: str | None = None
    attempt: conint(ge=1)
    priority: JobPriority
    correlation: JobCorrelation
    progress: JobProgress
    timestamps: JobTimestamps
    execution: JobExecution
    result: dict[str, Any] | None = None
    error: JobError | None = None
    links: JobLinks


class JobSubmissionReceipt(JobSnapshot):
    idempotent_replay: bool


class JobEventType(Enum):
    job_created = 'job.created'
    job_queued = 'job.queued'
    job_started = 'job.started'
    job_progress = 'job.progress'
    job_waiting = 'job.waiting'
    job_retry_scheduled = 'job.retry_scheduled'
    job_reclaimed = 'job.reclaimed'
    job_cancel_requested = 'job.cancel_requested'
    job_succeeded = 'job.succeeded'
    job_failed = 'job.failed'
    job_cancelled = 'job.cancelled'


class JobEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    event_id: UUID
    job_id: UUID
    type: JobEventType
    occurred_at: AwareDatetime
    attempt: conint(ge=1)
    data: dict[str, Any]


class JobEventPage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    snapshot: JobSnapshot
    events: list[JobEvent]
    next_cursor: UUID | None = None
    has_more: bool


class Type(Enum):
    input_provide = 'input.provide'
    approval_resolve = 'approval.resolve'
    job_resume = 'job.resume'


class JobAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type
    data: dict[str, Any]


class JobActionReceipt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_id: UUID
    idempotent_replay: bool
    job: JobSnapshot


class JobTypeCapability(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: str
    input_schema: str
    result_schema: str
    actions: list[str]


class EventDeliveryEnum(Enum):
    sse = 'sse'
    poll = 'poll'


class LeaseDefaults(BaseModel):
    duration_seconds: conint(ge=1)
    heartbeat_seconds: conint(ge=1)


class Retention(BaseModel):
    terminal_seconds: conint(ge=1) | None = None


class JobCapabilities(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocol_versions: list[str]
    priorities: list[JobPriority]
    statuses: list[JobStatus]
    event_delivery: list[EventDeliveryEnum]
    lease_defaults: LeaseDefaults
    retention: Retention
    job_types: list[JobTypeCapability]


class ErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: JobError
