/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getJobCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/events": {
        parameters: {
            query?: {
                after?: components["parameters"]["AfterCursor"];
            };
            header?: {
                "Last-Event-ID"?: components["parameters"]["LastEventId"];
            };
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get: operations["streamJobEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/events/poll": {
        parameters: {
            query?: {
                after?: components["parameters"]["AfterCursor"];
                limit?: number;
            };
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get: operations["pollJobEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/actions": {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["performJobAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        JobPriority: "interactive" | "normal" | "background" | "bulk";
        /** @enum {string} */
        JobStatus: "queued" | "running" | "waiting" | "retrying" | "succeeded" | "failed" | "cancelled";
        /** @enum {string} */
        WaitingReason: "input_required" | "approval_required" | "dependency_unavailable" | "connection_required" | "paused";
        JobCorrelationParent: {
            service: string;
            job_id: string;
        };
        JobCorrelation: {
            workflow_id?: string | null;
            parent?: components["schemas"]["JobCorrelationParent"] | null;
        } & {
            [key: string]: unknown;
        };
        JobSubmission: {
            type: string;
            priority: components["schemas"]["JobPriority"];
            /** Format: date-time */
            deadline_at?: string | null;
            correlation: components["schemas"]["JobCorrelation"];
            input: {
                [key: string]: unknown;
            };
        };
        JobProgress: {
            phase: string;
            message: string | null;
            completed_units: number | null;
            total_units: number | null;
        };
        JobTimestamps: {
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            queued_at: string;
            /** Format: date-time */
            started_at: string | null;
            /** Format: date-time */
            heartbeat_at: string | null;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            completed_at: string | null;
            /** Format: date-time */
            deadline_at: string | null;
            /** Format: date-time */
            expires_at: string | null;
            /** Format: date-time */
            next_attempt_at: string | null;
        };
        JobExecution: {
            claim_generation: number | null;
            /** Format: date-time */
            lease_expires_at: string | null;
        };
        JobError: {
            code: string;
            message: string;
            retryable: boolean;
            details?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        JobLinks: {
            self: string;
            events: string;
            events_poll: string;
            cancel: string;
            actions: string;
        };
        JobSnapshot: {
            /** @constant */
            protocol_version: "1.0";
            /** Format: uuid */
            job_id: string;
            job_type: string;
            status: components["schemas"]["JobStatus"];
            status_reason: string | null;
            attempt: number;
            priority: components["schemas"]["JobPriority"];
            correlation: components["schemas"]["JobCorrelation"];
            progress: components["schemas"]["JobProgress"];
            timestamps: components["schemas"]["JobTimestamps"];
            execution: components["schemas"]["JobExecution"];
            result: {
                [key: string]: unknown;
            } | null;
            error: components["schemas"]["JobError"] | null;
            links: components["schemas"]["JobLinks"];
        };
        JobSubmissionReceipt: components["schemas"]["JobSnapshot"] & {
            idempotent_replay: boolean;
        };
        /** @enum {string} */
        JobEventType: "job.created" | "job.queued" | "job.started" | "job.progress" | "job.waiting" | "job.retry_scheduled" | "job.reclaimed" | "job.cancel_requested" | "job.succeeded" | "job.failed" | "job.cancelled";
        JobEvent: {
            /** Format: uuid */
            event_id: string;
            /** Format: uuid */
            job_id: string;
            type: components["schemas"]["JobEventType"];
            /** Format: date-time */
            occurred_at: string;
            attempt: number;
            data: {
                [key: string]: unknown;
            };
        };
        JobEventPage: {
            snapshot: components["schemas"]["JobSnapshot"];
            events: components["schemas"]["JobEvent"][];
            /** Format: uuid */
            next_cursor: string | null;
            has_more: boolean;
        };
        JobAction: {
            /** @enum {string} */
            type: "input.provide" | "approval.resolve" | "job.resume";
            data: {
                [key: string]: unknown;
            };
        };
        JobActionReceipt: {
            /** Format: uuid */
            action_id: string;
            idempotent_replay: boolean;
            job: components["schemas"]["JobSnapshot"];
        };
        JobTypeCapability: {
            type: string;
            input_schema: string;
            result_schema: string;
            actions: string[];
        };
        JobCapabilities: {
            protocol_versions: string[];
            priorities: components["schemas"]["JobPriority"][];
            statuses: components["schemas"]["JobStatus"][];
            event_delivery: ("sse" | "poll")[];
            lease_defaults: {
                duration_seconds: number;
                heartbeat_seconds: number;
            };
            retention: {
                terminal_seconds: number | null;
            };
            job_types: components["schemas"]["JobTypeCapability"][];
        };
        ErrorResponse: {
            error: components["schemas"]["JobError"];
        };
    };
    responses: {
        /** @description Job is unknown, unauthorized, or expired. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Idempotency or lifecycle conflict. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Structurally invalid request or cursor. */
        InvalidRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        JobId: string;
        IdempotencyKey: string;
        AfterCursor: string;
        LastEventId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    submitJob: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobSubmission"];
            };
        };
        responses: {
            /** @description Idempotent replay of the original job. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSubmissionReceipt"];
                };
            };
            /** @description New job accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSubmissionReceipt"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["InvalidRequest"];
        };
    };
    getJobCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Supported protocol features and job types. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCapabilities"];
                };
            };
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current job snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSnapshot"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    streamJobEvents: {
        parameters: {
            query?: {
                after?: components["parameters"]["AfterCursor"];
            };
            header?: {
                "Last-Event-ID"?: components["parameters"]["LastEventId"];
            };
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Snapshot-first SSE stream followed by durable events and live heartbeats. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["InvalidRequest"];
        };
    };
    pollJobEvents: {
        parameters: {
            query?: {
                after?: components["parameters"]["AfterCursor"];
                limit?: number;
            };
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cursor-addressed durable event page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEventPage"];
                };
            };
        };
    };
    cancelJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Idempotent cancellation result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSnapshot"];
                };
            };
        };
    };
    performJobAction: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobAction"];
            };
        };
        responses: {
            /** @description Action receipt and current job state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobActionReceipt"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["InvalidRequest"];
        };
    };
}
